### ISSUE TITLE
Give a better error when perf.py is misconfigured

### ISSUE THREAD

**Issue by criccomini** [linkedin/Zopkio#16]
I accidentally set 'samza_job_0' instead of 'samza_instance_0' as a key in my perf.py machine logs list. This led to this exception:

    Traceback (most recent call last):
      File "/tmp/samza-test/samza-integration-tests/bin/zopkio", line 8, in <module>
        load_entry_point('zopkio==0.1.4', 'console_scripts', 'zopkio')()
      File "/tmp/samza-test/samza-integration-tests/lib/python2.7/site-packages/zopkio/__main__.py", line 114, in main
        test_runner.run()
      File "/tmp/samza-test/samza-integration-tests/lib/python2.7/site-packages/zopkio/test_runner.py", line 117, in run
        self._copy_logs()
      File "/tmp/samza-test/samza-integration-tests/lib/python2.7/site-packages/zopkio/test_runner.py", line 179, in _copy_logs
        logs = self.dynamic_config_module.machine_logs()[process.unique_id] + self.dynamic_config_module.naarad_logs()[process.unique_id]
    KeyError: 'samza_job_0'

It'd be nice if a better error were thrown (e.g. Unknown process id 'samza_job_0' found in machine log list).

**Comment by arpras** [comment]
Is this fixed ? Can we close this?
