### ISSUE TITLE
SSH passwords fail

### ISSUE THREAD

**Issue by criccomini** [linkedin/Zopkio#47]
Executing Zopkio with my SSH password, and no ~/.ssh/authorized_keys leads to:

    2015-01-14 10:03:02,437 zopkio.test_runner [ERROR] Aborting smoke-tests due to setup_suite failure:
    Traceback (most recent call last):
      File "/tmp/samza-tests/samza-integration-tests/lib/python2.7/site-packages/zopkio/test_runner.py", line 107, in run
        self.deployment_module.setup_suite()
      File "/tmp/samza-tests/scripts/deployment.py", line 88, in setup_suite
        'executable': c('samza_executable'),
      File "/tmp/samza-tests/scripts/samza_job_yarn_deployer.py", line 77, in install
        with get_ssh_client(host) as ssh:
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "/tmp/samza-tests/samza-integration-tests/lib/python2.7/site-packages/zopkio/remote_host_helper.py", line 200, in get_ssh_client
        ssh.connect(hostname, username=username, password=password)
      File "/tmp/samza-tests/samza-integration-tests/lib/python2.7/site-packages/paramiko/client.py", line 307, in connect
        look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
      File "/tmp/samza-tests/samza-integration-tests/lib/python2.7/site-packages/paramiko/client.py", line 519, in _auth
        raise saved_exception
    PasswordRequiredException: Private key file is encrypted

Running the same tests with --nopassword, and authroized_keys containing my public key works.

_NOTE: some of my deployment HAS already passed at the point that this failure occurs, so it appears that SFTP and SSH do work, but somehow this specific invocation is causing a problem._

**Comment by jdehrlich** [comment]
the problem can be resolved by modifying the samza_job_on_yarn_deployer, when you call get_ssh_client you can pass username=runtime.get_username() and password=runtime.get_password(). (this also works for get_sftp_client).
