### ISSUE TITLE
Be verbose on failures in adhoc deployer

### ISSUE THREAD

**Issue by criccomini** [linkedin/Zopkio#48]
It'd be nice if Zopkio gave more detail when adhoc deployer fails.

We saw this recently:

    2015-01-14 17:51:55,266 deployment [INFO] Deploying zookeeper_instance_0 on host: localhost
    2015-01-14 17:51:58,150 deployment [INFO] Deploying yarn_rm_instance_0 on host: localhost
    2015-01-14 17:52:03,546 zopkio.remote_host_helper [ERROR] 
    2015-01-14 17:52:03,548 zopkio.test_runner [ERROR] Aborting smoke-tests due to setup_suite failure:
    Traceback (most recent call last):
      File "/tmp/samza-test2/samza-integration-tests/lib/python2.7/site-packages/zopkio/test_runner.py", line 107, in run
        self.deployment_module.setup_suite()
      File "/tmp/samza-test2/scripts/deployment.py", line 76, in setup_suite
        'hostname': host
      File "/tmp/samza-test2/samza-integration-tests/lib/python2.7/site-packages/zopkio/deployer.py", line 78, in deploy
        self.start(unique_id, configs)
      File "/tmp/samza-test2/samza-integration-tests/lib/python2.7/site-packages/zopkio/adhoc_deployer.py", line 212, in start
        chan = exec_with_env(ssh, command, msg="Failed to start", env=env, sync=configs.get('sync', False))
      File "/tmp/samza-test2/samza-integration-tests/lib/python2.7/site-packages/zopkio/remote_host_helper.py", line 86, in exec_with_env
        return better_exec_command(ssh, new_command, msg)
      File "/tmp/samza-test2/samza-integration-tests/lib/python2.7/site-packages/zopkio/remote_host_helper.py", line 115, in better_exec_command
        raise ParamikoError(msg, err_msg)
    ParamikoError: Failed to start

Since adhoc deployer has the full channel when the failure occurs, it'd be nice if it dumped stderr and stdout so we knew what was going on. Right now it basically just says, "I got a non-zero exit code."

**Comment by criccomini** [comment]
Relates to https://issues.apache.org/jira/browse/SAMZA-511
