### ISSUE TITLE
Shutdown triggers exception

### ISSUE THREAD

**Issue by criccomini** [linkedin/Zopkio#49]
Occasionally, when Zopkio is shutting down after a test run, I see a stack trace at the very end of the execution. 

    Exception in thread Thread-33 (most likely raised during interpreter shutdown):
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 761, in run
      File "/tmp/samza-tests/samza-integration-tests/lib/python2.7/site-packages/kafka/util.py", line 108, in _timer
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 618, in wait
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 354, in wait
    <type 'exceptions.TypeError'>: 'NoneType' object is not callable

Everything appears to work. The report shows up in the browser with expected results. There's just an odd stack trace at the end.

**Comment by criccomini** [comment]
This could be a problem with Samza's Kafka consumer/producer usage, rather than a problem with Zopkio.

**Comment by criccomini** [comment]
Though, I think I've seen the issue with a non-Kafka stack trace as well. I'll keep my eye out.
