### ISSUE TITLE
Zopkio doesn't support __init__.py in test directories

### ISSUE THREAD

**Issue by criccomini** [linkedin/Zopkio#56]
I tried to add an __init__.py file in my test directory (./tests/__init__.py), and I get:

    Error setting up testrunner:
    Traceback (most recent call last):
      File "/tmp/samza-tests/samza-integration-tests/lib/python2.7/site-packages/zopkio/__main__.py", line 133, in main
        test_runner = TestRunner(args.testfile, args.test_list, config_overrides)
      File "/tmp/samza-tests/samza-integration-tests/lib/python2.7/site-packages/zopkio/test_runner.py", line 76, in __init__
        test_runner_helper.get_modules(testfile, tests_to_run, config_overrides)
      File "/tmp/samza-tests/samza-integration-tests/lib/python2.7/site-packages/zopkio/test_runner_helper.py", line 108, in get_modules
        test_dic = _parse_input(testfile)
      File "/tmp/samza-tests/samza-integration-tests/lib/python2.7/site-packages/zopkio/test_runner_helper.py", line 195, in _parse_input
        test_dic = utils.load_module(testfile).test
    AttributeError: 'module' object has no attribute 'test'

I'd like to be able to have my Zopkio tests be properly structured python packages, but I can't really do this without __init__.py files.

**Comment by arpras** [comment]
Leaving this open to address this enhanced check  brought by Joshua "this only determines that there is a file foo.py in directory foo, it will not handle the case of a different folder foo with an init.py that is also in the sys.path, might be worth adding a check for that"
